AllCops:
  TargetRubyVersion: 2.3
Style/Documentation:
  Enabled: false
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: []
    '%i': []
    '%w': []
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/TrailingBlankLines:
  EnforcedStyle: final_blank_line
Style/LambdaCall:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/AlignHash:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  # The IgnoreCopDirectives option causes the LineLength rule to ignore cop
  # directives like '# rubocop: enable ...' when calculating a line's length.
  IgnoreCopDirectives: false
Metrics/BlockLength:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
